[package]
name = "tpke-wasm"
version = "0.1.0-alpha.1"
authors = ["Piotr Roslaniec <p.roslaniec@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
categories = ["cryptography", "no-std"]
repository = "https://github.com/nucypher/ferveo"
description = "WASM bindings for group-threshold-cryptography crate"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
test-common = ["group-threshold-cryptography/test-common"]

[dependencies]
group-threshold-cryptography = { path = "../tpke", features = ["test-common", "api"]  }
ferveo-common = { path = "../ferveo-common" }
ferveo = { path = "../ferveo" }
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
console_error_panic_hook = { version = "0.1.7", optional = true }
wee_alloc = { version = "0.4.5" }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.0.1"
ark-serialize = { version = "0.4", features = ["derive"] }
js-sys = "0.3.61"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
console_error_panic_hook = "0.1.7"
rand_core = "0.6"

[package.metadata.cargo-machete]
ignore = ["getrandom"]
